local Players = game:GetService("Players")
local ServerStorage = game:GetService("ServerStorage")

local usernameCache = {}

local Config = require(script.Parent.Parent.Settings)

function getUsernameAsync(userid: number)
  if usernameCache[userid] then -- already cached, return
    return usernameCache[userid]
  end
  local success: boolean, resultOrError: string = pcall(function ()
    return Players:GetNameFromUserIdAsync(userid)
  end)
  if not success then
    if Config.DO_DEBUG then
      warn(("TopTimePlayed Board: Error retrieving username of userid %d. Cause: %s"):format(userid, resultOrError))
    end
    return "Name not found"
  else
    usernameCache[userid] = resultOrError
    return resultOrError
  end
end

local PlayAnimationInRig = {}

PlayAnimationInRig.currentId = -1
PlayAnimationInRig.animation = script.Parent.AnimationToPlay
PlayAnimationInRig.tag = script.Parent.FirstPlaceTag
PlayAnimationInRig.rig = script.Parent.Rig
PlayAnimationInRig.rigCopy = PlayAnimationInRig.rig:Clone()
PlayAnimationInRig.rigCopyStorage = ServerStorage:FindFirstChild("TopTimePlayedLeaderboard_DancingRigStorage")
if not PlayAnimationInRig.rigCopyStorage then
  PlayAnimationInRig.rigCopyStorage = Instance.new("Folder", ServerStorage)
  PlayAnimationInRig.rigCopyStorage.Name = "TopTimePlayedLeaderboard_DancingRigStorage"
end
PlayAnimationInRig.rigCopy.Parent = PlayAnimationInRig.rigCopyStorage

function PlayAnimationInRig.StopAnimationTrack()
  if PlayAnimationInRig.animationTrack then
    PlayAnimationInRig.animationTrack:Stop()
    PlayAnimationInRig.animationTrack = nil
  end
end

function PlayAnimationInRig.AnimateRig()
  PlayAnimationInRig.StopAnimationTrack()
  PlayAnimationInRig.humanoid = PlayAnimationInRig.rig.Humanoid
  PlayAnimationInRig.rigAnimator = PlayAnimationInRig.humanoid.Animator
  PlayAnimationInRig.animationTrack = PlayAnimationInRig.rigAnimator:LoadAnimation(PlayAnimationInRig.animation)
  PlayAnimationInRig.animationTrack.Looped = true
  PlayAnimationInRig.animationTrack:Play()
end

function PlayAnimationInRig.SetRigHumanoidDescription(userId: number)
  if PlayAnimationInRig.currentId == userId then return end
  PlayAnimationInRig.currentId = userId
  PlayAnimationInRig.StopAnimationTrack()
  PlayAnimationInRig.rig:Destroy()
  PlayAnimationInRig.rig = PlayAnimationInRig.rigCopy:Clone()
  PlayAnimationInRig.rig.Parent = script.Parent
  PlayAnimationInRig.AnimateRig()
  task.spawn(function ()
    local tries = 0
    local maxTries = 3
    local skip = false
    repeat
      local success, err = pcall(function ()
        local humanoidDescription
        local succ, err = pcall(function ()
          humanoidDescription = Players:GetHumanoidDescriptionFromUserId(userId)
          PlayAnimationInRig.humanoid:ApplyDescriptionReset(humanoidDescription)
        end)
        if not succ and Config.DO_DEBUG then
          warn(("TopTimePlayed Board: Failed to get humanoid description of userid %d. Cause: %s"):format(userId, err))
        end
        local tagClone = PlayAnimationInRig.tag:Clone()
        tagClone.Enabled = true
        tagClone.Parent = PlayAnimationInRig.rig.Head
        PlayAnimationInRig.humanoid.DisplayName = getUsernameAsync(userId)
      end)
      tries += 1
      if not success then warn(err) task.wait(1) end
      if success then skip = true end
    until tries > maxTries or skip == true
  end)
end

return PlayAnimationInRig
