--[[

PARTY LIGHTS AND LASERS! MAKE THE SCENERY LIVE!

These lights and lasers are very easy to set up, just put them on a desired
position, and you're good to go. However you will need a script that
will control what the lights will do.

There are presets provided under the PartyLights and Lasers groups, with
all the possible combinations already in place.

There are 24 possible presets on the party lights and 36 possible presets
on the lasers. For easy setup, just make a looping script that randomly sets
the preset value. An example script has also been provided!

These are very customizable, so you don't have to use a looping script or
strictly follow the presets, if you wish to make it controllable via DJ.

If you wish to add more lights and lasers, and use the preset scripts,
just add it in, within the same model group and name it to whatever,
such as "PartyLight7", "PartyLight8", and so on, and same idea applies for
the lasers as well.

Made by BangoutBoy (Pulsarnova)

]]
